---

- hosts: all

  tasks:    
    - name: Install node.js
      apt:
          name: nodejs
          state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Install redis
      apt:
        name: redis-server
        state: present

    - name: Setup redis database on the server
      command: chdir=/home/vagrant/redis-stable/src make install
      become: true

    - name: Install packages
      ansible.builtin.shell: npm i
      args:
        chdir: /home/vagrant/userapi
    
    - name: Run redis database
      command: redis-server
    
    - name: Test our app
      ansible.builtin.shell: npm test
      args: 
        chdir: /home/vagrant/userapi

    - name: Start our app
      ansible.builtin.shell: npm start 
      args: 
        chdir: /home/vagrant/userapi