Vagrant.configure("2") do |config|
    # Do not pay attention to this parameter
if Vagrant.has_plugin?("vagrant-vbguest")
  config.vm.provider :virtualbox do |vb|
    config.vbguest.auto_update = false
  end
end
 
  # define a VM machine configuration
  config.vm.define "project" do |server|
    server.vm.box = "ubuntu/bionic64"
     # Specify the VM ip address
    server.vm.network "private_network", ip: "192.168.56.10"
  
   # Specify the VM specs when using the Virtualbox provisioner
   server.vm.provider "virtualbox" do |vb|
     vb.name =  "project.server.local"
     # VM RAM in MB
     vb.memory = 2048
     # VM CPUs
     vb.cpus = 1
   end
   config.vm.provider "vmware_desktop" do |vmware|
     vmware.vmx["memsize"] = "2048"
     vmware.vmx["numvcpus"] = "1"
   end
 end
 config.vm.network "forwarded_port", guest: 3003, host: 3003
 # Use Vagrant Ansible provisioner
config.vm.provision "ansible_local" do |ansible|
  # The path to the playbooks entry point
  ansible.playbook = "playbooks/run.yml"

end
config.vm.synced_folder "../userapi", "/home/vagrant/userapi"

end


  
 